# Generated by Django 5.2.8 on 2025-11-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AP", "Andhra Pradesh"),
                    ("AR", "Arunachal Pradesh"),
                    ("AS", "Assam"),
                    ("BR", "Bihar"),
                    ("CT", "Chhattisgarh"),
                    ("GA", "Goa"),
                    ("GJ", "Gujarat"),
                    ("HR", "Haryana"),
                    ("HP", "Himachal Pradesh"),
                    ("JH", "Jharkhand"),
                    ("KA", "Karnataka"),
                    ("KL", "Kerala"),
                    ("MP", "Madhya Pradesh"),
                    ("MH", "Maharashtra"),
                ],
                help_text="Only required for State elections.",
                max_length=2,
                null=True,
            ),
        ),
    ]
