# Generated by Django 5.2.8 on 2025-11-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0007_remove_candidate_constituency_delete_constituency"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
